Make things in functions

diff --git a/src/install b/src/install
--- a/src/install
+++ b/src/install
@@ -1,30 +1,52 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-EFI_PARTITION="/dev/nvme0n1p1"
-ROOT_PARTITION="/dev/nvme0n1p2"
+usage() {
+    cat <<EOF
+Usage:
+    $0 --efi <EFI PARTITION> --root <ROOT PARTITION> [options]
+    
+Options:
+    Additional boot partition (if existing efi too small)
+    --xbootldr <XBOOTLDR PARTITION>
+}
+EOF
+}
 
-while [[ $# -gt 0 ]]; do
-    case $1 in
-        --efi)
-            EFI_PARTITION="$2"
-            shift 2
-            ;;
-        --xbootldr)
-            XBOOTLDR_PARTITION="$2"
-            shift 2
-            ;;
-        --root)
-            ROOT_PARTITION="$2"
-            shift 2
-            ;;
-        *)
-            echo "Unknown option: $1"
-            exit 1
-            ;;
-    esac
-done
+parse_args() {
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --efi)
+                EFI_PARTITION="$2"
+                shift 2
+                ;;
+            --xbootldr)
+                XBOOTLDR_PARTITION="$2"
+                shift 2
+                ;;
+            --root)
+                ROOT_PARTITION="$2"
+                shift 2
+                ;;
+            -h)
+                usage
+                exit 0
+                ;;
+            *)
+                echo "Unknown option: $1"
+                usage
+                exit 1
+                ;;
+        esac
+    done
+    [[ -v EFI_PARTITION && -v ROOT_PARTITION ]] || {
+        echo "Missing required option"
+        usage
+        exit 1
+    }
+}
 
+to_be_splitted() {
 echo "Configuration Summary:"
 echo "======================"
 echo "EFI partition:            $EFI_PARTITION"
@@ -189,3 +211,11 @@ umount /mnt
 cryptsetup close cryptroot
 
 echo "Don't forget to change the default passwords!"
+}
+
+main() {
+    parse_args "$@"
+    to_be_splitted
+}
+
+main "$@"
